SELECT TRG.TABLE_OWNER ,
       TRG.TABLE_NAME ,
       TRG.OWNER            AS TRIGGER_OWNER,
       TRG.TRIGGER_NAME,
       TRG.STATUS           AS TRIGGER_STATUS,
       DEP.REFERENCED_OWNER AS SEQUENCE_OWNER,
       DEP.REFERENCED_NAME  AS SEQUENCE_NAME,
       F_OID_COLUMN(trg.owner,trg.trigger_name) COLUNA_OID,
       DBMS_METADATA.GET_DDL('TRIGGER',TRG.TRIGGER_NAME,TRG.OWNER) AS SCRIPT,
       'CREATE OR REPLACE TRIGGER '||TRG.OWNER||'.'||TRG.TRIGGER_NAME||CHR(13)||
       'BEFORE INSERT ON '||TRG.TABLE_OWNER||'.'||TRG.TABLE_NAME||' FOR EACH ROW'||CHR(13)||
       'BEGIN'||CHR(13)||
       '     IF :NEW.'||F_OID_COLUMN(trg.owner,trg.trigger_name)||' IS NULL THEN'||CHR(13)||
       '        :NEW.'||F_OID_COLUMN(trg.owner,trg.trigger_name)||' := '||DEP.REFERENCED_NAME||'.NEXTVAL;'||CHR(13)||
       '     END IF;'||CHR(13)||
       'END;' AS NEW_SCRIPT
FROM DBA_TRIGGERS     TRG
      ,DBA_DEPENDENCIES DEP
 WHERE TRG.OWNER              = DEP.OWNER
   AND TRG.TRIGGER_NAME       = DEP.NAME
   AND DEP.REFERENCED_TYPE    = 'SEQUENCE'       
   AND TRG.OWNER           LIKE 'DB_CONTABILIDADE'
   AND TRIGGER_TEXT_LIKE(TRG.OWNER,TRG.TRIGGER_NAME,'%NEXTVAL%') = 1;
